/** @type {import('./env.mjs').Env} */
export const env = {
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL || '',
  NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '',
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY || '',
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY || '',
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY || process.env.NEXT_PUBLIC_STRIPE_PK || '',
  NEXT_PUBLIC_STRIPE_PK: process.env.NEXT_PUBLIC_STRIPE_PK || process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY || '',
  STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET || '',
  // Standardized Stripe Price IDs - canonical names only
  STRIPE_PRICE_STARTER: process.env.STRIPE_PRICE_STARTER || '',
  STRIPE_PRICE_TEAM: process.env.STRIPE_PRICE_TEAM || '',
  STRIPE_PRICE_PRO: process.env.STRIPE_PRICE_PRO || '',
  STRIPE_PRICE_SECURITY: process.env.STRIPE_PRICE_SECURITY || '',
  STRIPE_PRICE_ONE_TIME: process.env.STRIPE_PRICE_ONE_TIME || '',
  SENDGRID_API_KEY: process.env.SENDGRID_API_KEY || '',
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || '',
  NEXT_PUBLIC_URL: process.env.NEXT_PUBLIC_URL || '',
};
